definitions:
  handler.BaseResponse:
    properties:
      message:
        type: string
    type: object
  models.CreateRole:
    properties:
      description:
        $ref: '#/definitions/models.NameTranslations'
      name:
        $ref: '#/definitions/models.NameTranslations'
    type: object
  models.NameTranslations:
    properties:
      en:
        type: string
      ru:
        type: string
      uz:
        type: string
    required:
    - en
    - ru
    - uz
    type: object
host: localhost:4040
info:
  contact:
    email: khdiyz.12@gmail.com
    name: Diyorbek Hasanov
  description: API Server for Application
  title: Eduflow API
  version: "1.0"
paths:
  /api/v1/roles:
    post:
      consumes:
      - application/json
      description: Create Role
      parameters:
      - description: Create Role
        in: body
        name: create
        required: true
        schema:
          $ref: '#/definitions/models.CreateRole'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.BaseResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.BaseResponse'
      security:
      - ApiKeyAuth: []
      summary: Create Role
      tags:
      - Role
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
